/* eslint-disable eslint-comments/no-unlimited-disable */
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by laravel-typescriptable
declare namespace App.Models {
  export interface DocumentsInstitution {
    id: number
    code: string
    name: string
    reset_sn_period: string
    sn_template: string
    created_at?: string
    updated_at?: string
    letters_count?: number
    letters?: App.Models.DocumentsLetter[]
  }
  export interface DocumentsLetter {
    id: string
    institution_id: number
    classification_id: number
    sn?: number
    letter_number?: string
    subject: string
    public: boolean
    recipient?: string
    letter_date: string
    file_path?: string
    voided_at?: string
    issued_at?: string
    created_at?: string
    updated_at?: string
    created_by: number
    status?: string
    month?: number
    year?: number
    day?: number
    institution?: App.Models.DocumentsInstitution
    classification?: App.Models.DocumentsClassification
    creator?: App.Models.User
  }
  export interface DocumentsClassification {
    id: number
    code: string
    name: string
    parent_id?: number
    classification_separator: string
    created_at?: string
    updated_at?: string
    long_code?: string
    letters_count?: number
    letters?: App.Models.DocumentsLetter[]
    parent?: App.Models.DocumentsClassification
  }
  export interface MessagingMessage {
    id: string
    sender_id: number
    subject: string
    body: string
    created_at?: string
    updated_at?: string
    recipients_count?: number
    attachments_count?: number
    sender?: App.Models.User
    recipients?: App.Models.User[]
    attachments?: App.Models.MessagingAttachment[]
  }
  export interface MessagingRecipient {
    id: number
    message_id: string
    recipient_id: number
    read_at?: string
    created_at?: string
    updated_at?: string
    deleted_at?: string
    message?: App.Models.MessagingMessage
    recipient?: App.Models.User
  }
  export interface MessagingAttachment {
    id: number
    message_id: string
    file_path: string
    original_name: string
    created_at?: string
    updated_at?: string
    message?: App.Models.MessagingMessage
  }
  export interface User {
    id: number
    name: string
    email: string
    email_verified_at?: string
    password: string
    remember_token?: string
    created_at?: string
    updated_at?: string
    all_permissions?: any
    sent_messages_count?: number
    tokens_count?: number
    notifications_count?: number
    roles_count?: number
    sentMessages?: App.Models.MessagingMessage[]
    tokens?: any[]
    notifications?: any[]
    roles?: any[]
  }
}

declare namespace App {
  export interface PaginateLink {
    url: string
    label: string
    active: boolean
  }
  export interface Paginate<T = any> {
    data: T[]
    current_page: number
    first_page_url: string
    from: number
    last_page: number
    last_page_url: string
    links: App.PaginateLink[]
    next_page_url: string
    path: string
    per_page: number
    prev_page_url: string
    to: number
    total: number
  }
  export interface ApiPaginate<T = any> {
    data: T[]
    links: {
      first?: string
      last?: string
      prev?: string
      next?: string
    }
    meta: {
      current_page: number
      from: number
      last_page: number
      links: App.PaginateLink[]
      path: string
      per_page: number
      to: number
      total: number
    }
  }
}
